<?php

/**
 * @file
 * Contains mxt_notification.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mxt_notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mxt_notification module.
    case 'help.page.mxt_notification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MXT Notification Entity') . '</p>';
      return $output;

    default:
  }
}
